### ISSUE TITLE
Use lint-staged instead of linting everything on every commit

### ISSUE THREAD

**Issue by satazor** [uphold/uphold-scripts#46]
Currently, `uphold-scripts` recommends setting up a pre-commit hook that runs `lint`. However, `lint` runs in every file, which is slow for medium to large projects.

Instead, we could use `lint-staged`.

**Comment by waldyrious** [comment]
For the record, there's already a PR for this: #12.

**Comment by satazor** [comment]
Thank you @waldyrious

**Comment by satazor** [comment]
#12 was merged, closing
